In [12]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

master_df = pd.read_csv(
    "../data/processed/master_dataset.csv"
)

master_df['DATE_TIME'] = pd.to_datetime(
    master_df['DATE_TIME']
)

print("Master dataset loaded successfully")

display(master_df.head())

Master dataset loaded successfully

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0,25.184316,22.857507,0.0
1,2020-05-15,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0,25.184316,22.857507,0.0
2,2020-05-15,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0,25.184316,22.857507,0.0
3,2020-05-15,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0,25.184316,22.857507,0.0
4,2020-05-15,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0,25.184316,22.857507,0.0

In [13]:
master_df['HOUR'] = master_df['DATE_TIME'].dt.hour

master_df['DAY'] = master_df['DATE_TIME'].dt.day

master_df['MONTH'] = master_df['DATE_TIME'].dt.month

master_df['DAY_OF_WEEK'] = master_df['DATE_TIME'].dt.dayofweek

master_df['WEEK_OF_YEAR'] = master_df['DATE_TIME'].dt.isocalendar().week

print("Time features created successfully")

display(master_df.head())

Time features created successfully

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION,HOUR,DAY,MONTH,DAY_OF_WEEK,WEEK_OF_YEAR
0,2020-05-15,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0,25.184316,22.857507,0.0,0,15,5,4,20
1,2020-05-15,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0,25.184316,22.857507,0.0,0,15,5,4,20
2,2020-05-15,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0,25.184316,22.857507,0.0,0,15,5,4,20
3,2020-05-15,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0,25.184316,22.857507,0.0,0,15,5,4,20
4,2020-05-15,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0,25.184316,22.857507,0.0,0,15,5,4,20

In [14]:
master_df['IS_PEAK_HOUR'] = np.where(
    (master_df['HOUR'] >= 10) &
    (master_df['HOUR'] <= 15),
    1,
    0
)

display(master_df.head())

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION,HOUR,DAY,MONTH,DAY_OF_WEEK,WEEK_OF_YEAR,IS_PEAK_HOUR
0,2020-05-15,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0,25.184316,22.857507,0.0,0,15,5,4,20,0
1,2020-05-15,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0,25.184316,22.857507,0.0,0,15,5,4,20,0
2,2020-05-15,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0,25.184316,22.857507,0.0,0,15,5,4,20,0
3,2020-05-15,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0,25.184316,22.857507,0.0,0,15,5,4,20,0
4,2020-05-15,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0,25.184316,22.857507,0.0,0,15,5,4,20,0

In [15]:
master_df['TEMP_DIFFERENCE'] = (
    master_df['MODULE_TEMPERATURE']
    -
    master_df['AMBIENT_TEMPERATURE']
)

display(master_df.head())

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION,HOUR,DAY,MONTH,DAY_OF_WEEK,WEEK_OF_YEAR,IS_PEAK_HOUR,TEMP_DIFFERENCE
0,2020-05-15,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0,25.184316,22.857507,0.0,0,15,5,4,20,0,-2.326809
1,2020-05-15,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0,25.184316,22.857507,0.0,0,15,5,4,20,0,-2.326809
2,2020-05-15,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0,25.184316,22.857507,0.0,0,15,5,4,20,0,-2.326809
3,2020-05-15,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0,25.184316,22.857507,0.0,0,15,5,4,20,0,-2.326809
4,2020-05-15,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0,25.184316,22.857507,0.0,0,15,5,4,20,0,-2.326809

In [16]:
master_df['IRRADIATION_EFFICIENCY'] = (
    master_df['AC_POWER']
    /
    (master_df['IRRADIATION'] + 0.0001)
)

display(master_df.head())

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION,HOUR,DAY,MONTH,DAY_OF_WEEK,WEEK_OF_YEAR,IS_PEAK_HOUR,TEMP_DIFFERENCE,IRRADIATION_EFFICIENCY
0,2020-05-15,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0,25.184316,22.857507,0.0,0,15,5,4,20,0,-2.326809,0.0
1,2020-05-15,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0,25.184316,22.857507,0.0,0,15,5,4,20,0,-2.326809,0.0
2,2020-05-15,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0,25.184316,22.857507,0.0,0,15,5,4,20,0,-2.326809,0.0
3,2020-05-15,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0,25.184316,22.857507,0.0,0,15,5,4,20,0,-2.326809,0.0
4,2020-05-15,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0,25.184316,22.857507,0.0,0,15,5,4,20,0,-2.326809,0.0

In [17]:
master_df = master_df.sort_values(
    by='DATE_TIME'
)

master_df['PREVIOUS_AC_POWER'] = (
    master_df['AC_POWER'].shift(1)
)

display(master_df.head())

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION,HOUR,DAY,MONTH,DAY_OF_WEEK,WEEK_OF_YEAR,IS_PEAK_HOUR,TEMP_DIFFERENCE,IRRADIATION_EFFICIENCY,PREVIOUS_AC_POWER
0,2020-05-15,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.000000,6.259559e+06,25.184316,22.857507,0.0,0,15,5,4,20,0,-2.326809,0.0,NaN
68777,2020-05-15,4136001,Et9kgGMDl729KT4,0.0,0.0,269.933333,1.704250e+06,27.004764,25.060789,0.0,0,15,5,4,20,0,-1.943975,0.0,0.0
68778,2020-05-15,4136001,IQ2d7wF4YD8zU1Q,0.0,0.0,3177.000000,1.994153e+07,27.004764,25.060789,0.0,0,15,5,4,20,0,-1.943975,0.0,0.0
68779,2020-05-15,4136001,LYwnQax7tkwH5Cb,0.0,0.0,1872.500000,1.794959e+09,27.004764,25.060789,0.0,0,15,5,4,20,0,-1.943975,0.0,0.0
68780,2020-05-15,4136001,LlT2YUhhzqhg5Sw,0.0,0.0,1094.357143,2.825928e+08,27.004764,25.060789,0.0,0,15,5,4,20,0,-1.943975,0.0,0.0

In [18]:
master_df.dropna(inplace=True)

print(master_df.isnull().sum())

DATE_TIME                 0
PLANT_ID                  0
SOURCE_KEY                0
DC_POWER                  0
AC_POWER                  0
DAILY_YIELD               0
TOTAL_YIELD               0
AMBIENT_TEMPERATURE       0
MODULE_TEMPERATURE        0
IRRADIATION               0
HOUR                      0
DAY                       0
MONTH                     0
DAY_OF_WEEK               0
WEEK_OF_YEAR              0
IS_PEAK_HOUR              0
TEMP_DIFFERENCE           0
IRRADIATION_EFFICIENCY    0
PREVIOUS_AC_POWER         0
dtype: int64

In [19]:
master_df['ROLLING_MEAN_AC_POWER'] = (
    master_df['AC_POWER']
    .rolling(window=3)
    .mean()
)

display(master_df.head())

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION,HOUR,DAY,MONTH,DAY_OF_WEEK,WEEK_OF_YEAR,IS_PEAK_HOUR,TEMP_DIFFERENCE,IRRADIATION_EFFICIENCY,PREVIOUS_AC_POWER,ROLLING_MEAN_AC_POWER
68777,2020-05-15,4136001,Et9kgGMDl729KT4,0.0,0.0,269.933333,1.704250e+06,27.004764,25.060789,0.0,0,15,5,4,20,0,-1.943975,0.0,0.0,NaN
68778,2020-05-15,4136001,IQ2d7wF4YD8zU1Q,0.0,0.0,3177.000000,1.994153e+07,27.004764,25.060789,0.0,0,15,5,4,20,0,-1.943975,0.0,0.0,NaN
68779,2020-05-15,4136001,LYwnQax7tkwH5Cb,0.0,0.0,1872.500000,1.794959e+09,27.004764,25.060789,0.0,0,15,5,4,20,0,-1.943975,0.0,0.0,0.0
68780,2020-05-15,4136001,LlT2YUhhzqhg5Sw,0.0,0.0,1094.357143,2.825928e+08,27.004764,25.060789,0.0,0,15,5,4,20,0,-1.943975,0.0,0.0,0.0
68781,2020-05-15,4136001,Mx2yZCDsyf6DPfv,0.0,0.0,5692.200000,2.453646e+06,27.004764,25.060789,0.0,0,15,5,4,20,0,-1.943975,0.0,0.0,0.0

In [20]:
master_df.dropna(inplace=True)

print(master_df.isnull().sum())

DATE_TIME                 0
PLANT_ID                  0
SOURCE_KEY                0
DC_POWER                  0
AC_POWER                  0
DAILY_YIELD               0
TOTAL_YIELD               0
AMBIENT_TEMPERATURE       0
MODULE_TEMPERATURE        0
IRRADIATION               0
HOUR                      0
DAY                       0
MONTH                     0
DAY_OF_WEEK               0
WEEK_OF_YEAR              0
IS_PEAK_HOUR              0
TEMP_DIFFERENCE           0
IRRADIATION_EFFICIENCY    0
PREVIOUS_AC_POWER         0
ROLLING_MEAN_AC_POWER     0
dtype: int64

In [21]:
print(master_df.columns)

print("\nFinal Shape:")
print(master_df.shape)

Index(['DATE_TIME', 'PLANT_ID', 'SOURCE_KEY', 'DC_POWER', 'AC_POWER',
       'DAILY_YIELD', 'TOTAL_YIELD', 'AMBIENT_TEMPERATURE',
       'MODULE_TEMPERATURE', 'IRRADIATION', 'HOUR', 'DAY', 'MONTH',
       'DAY_OF_WEEK', 'WEEK_OF_YEAR', 'IS_PEAK_HOUR', 'TEMP_DIFFERENCE',
       'IRRADIATION_EFFICIENCY', 'PREVIOUS_AC_POWER', 'ROLLING_MEAN_AC_POWER'],
      dtype='str')

Final Shape:
(136469, 20)

In [ ]:
master_df.to_csv(
    "../data/processed/featured_dataset.csv",
    index=False
)

print("Featured dataset saved successfully")